### ISSUE TITLE
Rate Limiting on Sports Reference

### ISSUE THREAD

**Issue by abramsmatthew99** [vishaalagartha/basketball_reference_scraper#100]
If you're noticing that you suddenly can't pull any data, odds are you were pulling too many pages too quickly. 

According to https://www.sports-reference.com/bot-traffic.html , as of October they have begun to rate limit to no more than 20 requests per minute. This should be an easy enough problem to get around now that we're aware, but just something to keep in mind.

**Comment by my7hai** [comment]
https://www.sports-reference.com/blog/2022/10/sports-reference-will-turn-off-our-widgets-service-january-1-2023/

it seems they turned it off completely. i really dont wanna rewrite my whole scraper :(

**Comment by abramsmatthew99** [comment]
> 

Agreed, this is gonna make my project a lot longer aha

**Comment by vishaalagartha** [comment]
This should be resolved with the new version's `last_request` time checking.
