### ISSUE TITLE
get_game_logs no longer works because of sports-reference dependency

### ISSUE THREAD

**Issue by tgracin** [vishaalagartha/basketball_reference_scraper#102]
function `get_game_logs` queries `r = get(f'https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url={suffix}%2Fgamelog%2F{year}%2F&div={selector}')`, but that widget is no longer supported. Here is a response (which has status_code 200, so the rest of the function believes it should be parsable):

`b'document.write(\'<div class="sr_widget" style="overflow-x:auto">\');\ndocument.write(\'<p><strong>NOTE:</strong> <a href="https://www.sports-reference.com/blog/2022/10/sports-reference-will-turn-off-our-widgets-service-january-1-2023/">Sports Reference has turned off our widgets service effective January 1, 2023</a></p>\');\ndocument.write(\'</div>\');\n'`

The data should be fetched from somewhere else.

**Comment by josh-bone** [comment]
For reference: https://www.sports-reference.com/blog/2022/10/sports-reference-will-turn-off-our-widgets-service-january-1-2023/

**Comment by vishaalagartha** [comment]
This issue should be resolved with the new version
