### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by dheerajkattar** [vishaalagartha/basketball_reference_scraper#107]
Only get_roster() seems to work, any other function returns a ConnectionError:

gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:
...
--> 519     raise ConnectionError(e, request=request)
    521 except ClosedPoolError as e:
    522     raise ConnectionError(e, request=request)

ConnectionError: HTTPSConnectionPool(host='widgets.sports-reference.com', port=443): Max retries exceeded with url: /wg.fcgi?css=1&site=bbr&url=%2Fplayers%2Fj%2Fjamesle01%2Fgamelog%2F2016-01-01%2F&div=div_pgl_basic_playoffs (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x1BEE5AD8>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by JJnotJimmyJohn** [comment]
Widgets are retired by BBR. So any module that utilizes widgets won't work.

**Comment by vishaalagartha** [comment]
This issue should be resolved with the new version.
