### ISSUE TITLE
Player names with accents not rendering properly

### ISSUE THREAD

**Issue by TonyAttalla** [vishaalagartha/basketball_reference_scraper#16]
It could be how I'm dealing with the data, but some player names (Eg. "Kristaps Porziņģis", "Luka Dončić" are coming back with strange characters in place of the characters with accents on them when using get_roster() (Luka DonÄiÄ‡, for example).  I grabbed the function from here and tried messing around with the encoding and decoding, but no luck. I'm sure there's a workaround for this but I just can't figure it out.

**Comment by haykh** [comment]
As a sloppy solution I'd suggest reading straight from the website like this:
```python
df = pd.read_html("https://www.basketball-reference.com/teams/MIL/2015.html")
```
instead of 
```python
r = get(f'https://widgets.sports-reference.com/wg.fcgi?css=1&site=bbr&url=%2Fteams%2FMIL%2F2015.html&div=div_roster')
soup = BeautifulSoup(dd.content, 'html.parser')
table = soup.find('table')
df = pd.read_html(str(table))[0]
```
But that way you'd have to change this everywhere in the code to be consistent.
