### ISSUE TITLE
Any plan to add more endpoint like advanced?

### ISSUE THREAD

**Issue by timxymo** [vishaalagartha/basketball_reference_scraper#19]
Just wondering if there are any plans to keep adding tables/endpoints like **[Advanced](https://www.basketball-reference.com/players/d/doncilu01.html#all_advanced)**? Great module regardless!

**Comment by vishaalagartha** [comment]
Thanks! What do you mean specifically by Advanced stats? If you check out the [API](https://github.com/vishaalagartha/basketball_reference_scraper/blob/master/API.md), you can already pass `ADVANCED` to the `data_format` variable for many endpoints.

**Comment by timxymo** [comment]
You're right! I guess I didn't think it would be under ```stat_type```, but that's exactly what I'm looking for!
