### ISSUE TITLE
Identify players with same name or same name different suffix

### ISSUE THREAD

**Issue by timxymo** [vishaalagartha/basketball_reference_scraper#20]
I had trouble scraping Jaren Jackson Jr's data using function ```get_stats( )```, I think it returns his dad. I also tried to input ```'Jaren Jackson Jr.' ```but it returns the same result, not sure if you remove the suffix in the source code. Any workaround? Thanks

**Comment by vishaalagartha** [comment]
Check out version 1.0.12 for the fixed version! Thanks for pointing this out.
