### ISSUE TITLE
Duplicate player names returns only the first match

### ISSUE THREAD

**Issue by jeffreykennethli** [vishaalagartha/basketball_reference_scraper#24]
In utils.py get_player_suffix, only the first player name match is returned, which fails when there are players with the same names, for example, Dee Brown:

https://www.basketball-reference.com/players/b/brownde01.html
https://www.basketball-reference.com/players/b/brownde03.html

You might add a get_players method which returns a list of dfs for each player that matches, since there aren't that many players with duplicates at the moment (by my count, there are only doubles, not triples, and <20 in the past 30 years).

**Comment by skandasastry** [comment]
Piggy backing onto this, it might just be better to offer an option to search using basketball reference's "slugs", which basically provide a unique id for each player. For example, LeBron James' slug is: jamesle01, and as you can see in the Dee Brown urls, they  are distinguished by different numbers at the end of their slug.

**Comment by vishaalagartha** [comment]
closed at cbbdcd2
