### ISSUE TITLE
Full 2020 Season Schedule Not Displaying

### ISSUE THREAD

**Issue by philipbolin98** [vishaalagartha/basketball_reference_scraper#25]
When I use the function get_schedule(2020, playoffs=False), it returns the schedule from the season opener through 2019-10-31 but no games afterward. This seems to be the only season in which this is the case.

Thanks!

**Comment by vishaalagartha** [comment]
This was caused by the strange season schedule, but should be fixed now in v1.0.19. Thanks for bringing it to my attention!

**Comment by philipbolin98** [comment]
Thanks for the quick update! I figured it was because of the weird covid schedule. However it still seems that the function isnt returning the games that were played in March and July. Thanks again!

**Comment by vishaalagartha** [comment]
No worries! Let me know if you run into any other issues or can think of any enhancements.
