### ISSUE TITLE
Can't get playoff game logs for players to work 

### ISSUE THREAD

**Issue by Mor880** [vishaalagartha/basketball_reference_scraper#26]
Hi all,

Bear with me, I'm very novice with Python and instead of finding out how to scrape Basketball-Reference myself I figured why not try this module first. 

The game logs for regular season games seem to work fine using `get_game_logs('LaMarcus Aldridge', '2013-04-20', '2017-08-01', playoffs=False)`, but if I want to look at playoff game logs and do `get_game_logs('LaMarcus Aldridge', '2013-04-20', '2017-08-01', playoffs=True)` I get the following error on the first try:

> C:\Users\myname\Anaconda3\lib\site-packages\pandas\core\ops\__init__.py:1115: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  result = method(y)

What I get is an empty Pandas Dataframe. I also tried this with Damian Lillard and it also didn't work.

Am I doing something wrong? 

P.S I tried `get_game_logs('LeBron James', '2006-04-01', '2020-11-01', True)`  and this seems to work partially, I get a Dataframes containing the latest game logs, the only problem is that all game logs before 2011 are missing.

**Comment by vishaalagartha** [comment]
Closed at 175d44b
