### ISSUE TITLE
get_roster crashes when NaN name appears in the team's roster table

### ISSUE THREAD

**Issue by giasemidis** [vishaalagartha/basketball_reference_scraper#30]
Miami Heat 2021 roster is given [here](https://www.basketball-reference.com/teams/MIA/2021.html). The table contains an empty row which causes the `get_roster` to crash because  `remove_accents(name, team, season_end_year)` finds a NaN instead of a string. One solution would be to remove the nan Players in the `get_roster` one line above, e.g.
```
        df = df[df['PLAYER'].notna()]
        df['PLAYER'] = df['PLAYER'].apply(lambda name: remove_accents(name, team, season_end_year))
```
it should also be combined with another update on `utils.remove_accents`, for example line 54 should be 
```
matches = sum(l1 == l2 for l1, l2 in zip(p, name)) if pd.notna(p) else 0
```
by the way, what is the utility of `remove_accents()` function?

![image](https://user-images.githubusercontent.com/23743685/102159592-c1e76900-3e7b-11eb-814a-2549f815ed00.png)

**Comment by vishaalagartha** [comment]
`remove_accents` simplifies the return value of pandas dataframe since python doesn't handle accents well.

**Comment by giasemidis** [comment]
Thanks for you reply and the great work. Why the accents handling is not done using something like this `unicodedata.normalize('NFD', anchor.text).encode('ascii', 'ignore').decode("utf-8").lower()` which is used in the `get_player_suffix()`? It seems to be easier and avoids an extra request to the webpage. I apologise if do not understand the purpose fully. 

In relation to the issue reported above, I spotted another issue for the Memphis roster in 2021, i.e.
`roster = get_roster('MEM', 2021)`.  This is the roster on [basketnall-reference](https://www.basketball-reference.com/teams/MEM/2021.html).
![image](https://user-images.githubusercontent.com/23743685/102690674-f1d99800-41fe-11eb-987d-64c6fa8c4716.png)

There is a row with the Player name filled but all other fields empty. This returns a np.nan, which when the lambda functions apply in `get_roster()`, it crashes because `x` is a float and `x.upper` cannot be applied.
```
        df['BIRTH_DATE'] = df['BIRTH_DATE'].apply(lambda x: pd.to_datetime(x))
        df['NATIONALITY'] = df['NATIONALITY'].apply(lambda x: x.upper())
```

My full solution is the following in the `get_roster()`
```
         # remove rows with no player name (this was the issue above)
        df = df[df['PLAYER'].notna()]
        df['PLAYER'] = df['PLAYER'].apply(lambda name: remove_accents(name, team, season_end_year))
        # handle rows with empty fields but with a player name.
        df['BIRTH_DATE'] = df['BIRTH_DATE'].apply(lambda x: pd.to_datetime(x) if pd.notna(x) else pd.NaT)
        df['NATIONALITY'] = df['NATIONALITY'].apply(lambda x: x.upper() if pd.notna(x) else '')
```
Personally, I have commented out the line `df['PLAYER'] = df['PLAYER'].apply(lambda name: remove_accents(name, team, season_end_year))` as it causes some issues that I haven't yet resolved. Without it it still works fine.

**Comment by vishaalagartha** [comment]
@giasemidis , I would love any contributions! Feel free to fork the repo and create any PR's you deem helpful.
