### ISSUE TITLE
Can't get game logs for 2020-2021 season

### ISSUE THREAD

**Issue by powdrild** [vishaalagartha/basketball_reference_scraper#35]
When running the following code:
```
game = get_game_logs('Chris Paul', '2020-12-22', '2020-12-30', playoffs=False)
print(game)
```

The output is:
```
Results for Chris Paul:

Empty DataFrame
Columns: [DATE, AGE, TEAM, HOME/AWAY, OPPONENT, RESULT, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, GAME_SCORE, +/-]
Index: []
```

 I can pull game logs from previous seasons with no problem using the method above. Please let me know if I am not using the function correctly.

EDIT: I was able to get Blake Griffin's and Jamal Murray's 2020-2021 game log, but haven't been able to obtain any others for this season yet.

**Comment by vishaalagartha** [comment]
Closed at commit 175d44b
