### ISSUE TITLE
Can't set ask_matches = False. 

### ISSUE THREAD

**Issue by Liam-McLeod** [vishaalagartha/basketball_reference_scraper#49]
For get_stats in players.py. If I do get_stats('Stephen Curry', 'PER_GAME', False, False, False) I get the error that get_stats only takes 1 to 4 arguments. If i specify ask_matches= False, I get the error that ask_matches is an unexpected keyword argument. Is there anyway to turn the option ask_matches off?

**Comment by Liam-McLeod** [comment]
For get_stats in players.py. If I do get_stats('Stephen Curry', 'PER_GAME', False, False, False) I get the error that get_stats only takes 1 to 4 arguments. If i specify ask_matches= False, I get the error that ask_matches is an unexpected keyword argument. Is there anyway to turn the option ask_matches off?

**Comment by vishaalagartha** [comment]
Closed at #50 .
