### ISSUE TITLE
Parameters 'RANK' and 'Y/Y' return error

### ISSUE THREAD

**Issue by adoreste319** [vishaalagartha/basketball_reference_scraper#7]
Various functions state that the data format can be 'RANK' or 'Y/Y'; however, when ran as such it returns either 'ValueError: No tables found' or 'UnboundLocalError: local variable 'selector' referenced before assignment'. What is the proper usage for RANK and what is the 'Y/Y' data format?

**Comment by vishaalagartha** [comment]
This was a valid parameter in a previous version of the package. It is now deprecated and the documentation has been updated appropriately. Thanks for pointing it out!
